import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  checkPackageManagerField,
  detect,
  fileExists,
  getLockfileMatches,
} from '../src/detect/index.js';
import { PackageJson } from '../src/types.js';

const YARN_CLASSIC_LOCK = '# yarn lockfile v1\n\n\nsome-package@^1.0.0:\n  version "1.0.0"\n';
const YARN_BERRY_LOCK =
  '# This file is generated by running "yarn install"\n\n__metadata:\n  version: 6\n';

describe('detect module', () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'debtctl-test-'));
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  const writePackageJson = async (contents: PackageJson): Promise<void> => {
    await fs.writeFile(path.join(tempDir, 'package.json'), JSON.stringify(contents));
  };

  const writeLockfile = async (name: string, contents = ''): Promise<void> => {
    await fs.writeFile(path.join(tempDir, name), contents);
  };

  describe('fileExists', () => {
    it('should return true when the file exists', async () => {
      const filePath = path.join(tempDir, 'present.txt');
      await fs.writeFile(filePath, 'hello');
      expect(await fileExists(filePath)).toBe(true);
    });

    it('should return false when the file does not exist', async () => {
      const filePath = path.join(tempDir, 'missing.txt');
      expect(await fileExists(filePath)).toBe(false);
    });
  });

  describe('checkPackageManagerField', () => {
    it('should return npm when packageManager is "npm@x"', async () => {
      await writePackageJson({ packageManager: 'npm@10.2.0' });
      expect(await checkPackageManagerField(tempDir)).toEqual({
        manager: 'npm',
        version: '10.2.0',
        source: 'packageManager-field',
      });
    });

    it('should return pnpm when packageManager is "pnpm@x"', async () => {
      await writePackageJson({ packageManager: 'pnpm@9.1.0' });
      expect(await checkPackageManagerField(tempDir)).toEqual({
        manager: 'pnpm',
        version: '9.1.0',
        source: 'packageManager-field',
      });
    });

    it('should return yarn-classic when packageManager is "yarn@1.x"', async () => {
      await writePackageJson({ packageManager: 'yarn@1.22.19' });
      expect(await checkPackageManagerField(tempDir)).toEqual({
        manager: 'yarn-classic',
        version: '1.22.19',
        source: 'packageManager-field',
      });
    });

    it('should return yarn-berry when packageManager is yarn at a non-1.x version', async () => {
      await writePackageJson({ packageManager: 'yarn@4.1.0' });
      expect(await checkPackageManagerField(tempDir)).toEqual({
        manager: 'yarn-berry',
        version: '4.1.0',
        source: 'packageManager-field',
      });
    });

    it('should return null when the packageManager field is missing', async () => {
      await writePackageJson({ name: 'no-pm-field' });
      expect(await checkPackageManagerField(tempDir)).toBeNull();
    });

    it('should return null when the manager name is unknown', async () => {
      await writePackageJson({ packageManager: 'bun@1.0.0' });
      expect(await checkPackageManagerField(tempDir)).toBeNull();
    });
  });

  describe('getLockfileMatches', () => {
    it('should return the npm manager when only package-lock.json exists', async () => {
      await writeLockfile('package-lock.json');
      const matches = await getLockfileMatches(tempDir);
      expect(matches.map((manager) => manager.id)).toEqual(['npm']);
    });

    it('should return the pnpm manager when only pnpm-lock.yaml exists', async () => {
      await writeLockfile('pnpm-lock.yaml');
      const matches = await getLockfileMatches(tempDir);
      expect(matches.map((manager) => manager.id)).toEqual(['pnpm']);
    });

    it('should return yarn-classic when yarn.lock has the v1 header', async () => {
      await writeLockfile('yarn.lock', YARN_CLASSIC_LOCK);
      const matches = await getLockfileMatches(tempDir);
      expect(matches.map((manager) => manager.id)).toEqual(['yarn-classic']);
    });

    it('should return yarn-berry when yarn.lock contains __metadata:', async () => {
      await writeLockfile('yarn.lock', YARN_BERRY_LOCK);
      const matches = await getLockfileMatches(tempDir);
      expect(matches.map((manager) => manager.id)).toEqual(['yarn-berry']);
    });

    it('should return an empty array when no lockfiles exist', async () => {
      const matches = await getLockfileMatches(tempDir);
      expect(matches).toEqual([]);
    });

    it('should return multiple matches when several lockfiles are present', async () => {
      await writeLockfile('package-lock.json');
      await writeLockfile('yarn.lock', YARN_CLASSIC_LOCK);
      const matches = await getLockfileMatches(tempDir);
      expect(matches.map((manager) => manager.id)).toEqual(['npm', 'yarn-classic']);
    });
  });

  describe('detect', () => {
    it('should prefer the packageManager field over lockfiles', async () => {
      await writePackageJson({ packageManager: 'pnpm@9.1.0' });
      await writeLockfile('package-lock.json');
      const result = await detect(tempDir);
      expect(result).toEqual({
        manager: 'pnpm',
        version: '9.1.0',
        source: 'packageManager-field',
      });
    });

    it('should fall back to the lockfile when packageManager field is absent', async () => {
      await writePackageJson({ name: 'lockfile-only' });
      await writeLockfile('pnpm-lock.yaml');
      const result = await detect(tempDir);
      expect(result).toEqual({ manager: 'pnpm', source: 'lockfile' });
    });

    it('should throw when no packageManager field and no lockfiles', async () => {
      await writePackageJson({ name: 'nothing-here' });
      await expect(detect(tempDir)).rejects.toThrow(/Could not detect package manager/);
    });

    it('should populate ambiguous when multiple lockfiles are present', async () => {
      await writePackageJson({ name: 'ambiguous' });
      await writeLockfile('package-lock.json');
      await writeLockfile('yarn.lock', YARN_CLASSIC_LOCK);
      const result = await detect(tempDir);
      expect(result.manager).toBe('npm');
      expect(result.source).toBe('lockfile');
      expect(result.ambiguous).toEqual(['package-lock.json', 'yarn.lock']);
    });

    it('should use MANAGERS priority order when picking from ambiguous lockfiles', async () => {
      await writePackageJson({ name: 'priority' });
      await writeLockfile('pnpm-lock.yaml');
      await writeLockfile('yarn.lock', YARN_CLASSIC_LOCK);
      const result = await detect(tempDir);
      expect(result.manager).toBe('pnpm');
      expect(result.ambiguous).toEqual(['pnpm-lock.yaml', 'yarn.lock']);
    });

    it('should omit ambiguous when exactly one lockfile matches', async () => {
      await writePackageJson({ name: 'single-lock' });
      await writeLockfile('package-lock.json');
      const result = await detect(tempDir);
      expect(result.ambiguous).toBeUndefined();
    });
  });
});
